this wasn't required

diff --git a/xulrunner-1.9.2/Makefile.songbird b/xulrunner-1.9.2/Makefile.songbird
--- a/xulrunner-1.9.2/Makefile.songbird
+++ b/xulrunner-1.9.2/Makefile.songbird
@@ -104,6 +104,13 @@ xr-clean: FORCE
 
 xr-packaging-%:
 	@echo "Packaging up $*-mode $(SB_VENDOR_TARGET)..."
+	@if test "release" = "$*"; then \
+      if $(HAVE_XR_release_BUILD); then \
+         cd $(CURDIR)/mozilla && $(XR_STRIP_SYMBOLS) $(SB_XR_PLATFORM); \
+      else \
+         echo "Could not find release build to strip symbols in. Skipping." 1>&2; \
+      fi; \
+   fi
 	@if $(HAVE_XR_$*_BUILD); then \
       $(call sh_make,$(XR_PACKAGE_DEPS) $(SB_XR_PLATFORM)-$(SB_XR_ARCH) $(SB_BRANCH) $*); \
       $(call sh_make,$(RM) -r $(SB_VENDOR_BINARIES_DIR)/mozilla-1.9.2/$*); \
